name: Build Lilit APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev libssl-dev python3-setuptools
      - name: Build with Buildozer
        uses: ArtemShatalov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer -v android debug
